///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace JenkinsTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the JenkinsTestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
    [RepositoryFolder("2f541aa1-67d0-4254-a665-6db3bf32ce32")]
    public partial class JenkinsTestRepository : RepoGenBaseFolder
    {
        static JenkinsTestRepository instance = new JenkinsTestRepository();

        /// <summary>
        /// Gets the singleton class instance representing the JenkinsTestRepository element repository.
        /// </summary>
        [RepositoryFolder("2f541aa1-67d0-4254-a665-6db3bf32ce32")]
        public static JenkinsTestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public JenkinsTestRepository() 
            : base("JenkinsTestRepository", "/", null, 0, false, "2f541aa1-67d0-4254-a665-6db3bf32ce32", ".\\RepositoryImages\\JenkinsTestRepository2f541aa1.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("2f541aa1-67d0-4254-a665-6db3bf32ce32")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
    public partial class JenkinsTestRepositoryFolders
    {
    }
#pragma warning restore 0436
}